package com.hackfest.quaranteams.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "UserDetails")
public class BasicDetails {
	
	@DynamoDBHashKey  (attributeName = "aadhar")
    private String aadhar;
    @DynamoDBAttribute
    private String pancard;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private List<BankDetails> bankDetails;
    
    private String error;

}
